#!/bin/sh

if [[ $(git branch | wc -l) =~ 0 ]]; then exit 0;fi

# ブランチ名取得
issue=`git rev-parse --abbrev-ref HEAD | perl -ne 'print $1 if /(PTKPCRON-\d+)/'`

if [ ! $issue ]; then
  exit 0
fi


# git commit 時にエディタ起動した場合にのみ、ブランチ名を出力する
massage="$(cat $1)"
if [[ "$massage" =~ "[$issue]" ]]; then
  echo "$massage" > $1
else
  echo "[$issue] $massage" > $1
fi
