#!/bin/sh
set -eu

git_root=`git rev-parse --show-toplevel 2> /dev/null`;

if [ "$git_root" == "" ]; then
  echo This does not appear to be a git repo.
  exit 1
fi

basename=${0##*/}

for hook in `find ~/.git_template/hooks/scripts/$basename -maxdepth 1 -type l`
do
  $hook $@
  if [ $? != 0 ]; then
    exit 1;
  fi
done
