#!/bin/sh
self_dirname=`dirname $0`
self_basename=`basename $0`
for hook in `find ${self_dirname}/scripts/${self_basename}/ -maxdepth 1 -type f`
do
  $hook $1
  if [ $? != 0 ]; then
    exit 1;
  fi
done

