#!/bin/sh
self_basename=`basename $0`
for hook in `find ~/.git_template/hooks/scripts/${self_basename}/* -maxdepth 1 -type f -or -type l`
do
  echo $hook
  $hook $1
  if [ $? != 0 ]; then
    exit 1;
  fi
done
