#!/bin/sh
set -eu

git_root=`git rev-parse --show-toplevel 2> /dev/null`;

if [ "$git_root" == "" ]; then
  echo This does not appear to be a git repo.
  exit 1
fi

basename=${0##*/}
remote_name=$1;
remote_url=$2;

for hook in `find ~/.homesick/repos/user_conf/home/.git_template/hooks/scripts/$basename/ -maxdepth 1 -type f`
do
  $hook $remote_name $remote_url
  if [ $? != 0 ]; then
    exit 1;
  fi
done
