#!/bin/bash
# Looks for changes to Gemfile[.lock] or package.json, and automates running bundle and other tasks.
# https://gist.github.com/stefansundin/82051ad2c8565999b914

function changed {
  git diff --name-only HEAD@{2} HEAD | grep "^$1" > /dev/null 2>&1
}

if changed 'Gemfile.*'; then
  echo "Gemfile changed, bundling"
  bundle check || bundle install
  [[ -d 'tmp' ]] && touch 'tmp/restart.txt'
fi

if changed 'bower.json'; then
  echo "bower.json changed, installing"
  bower install
fi

if changed 'db/migrate'; then
  echo "Migrations pending, migrating"
  bundle exec rake db:migrate RAILS_ENV=development
  bundle exec rake db:migrate RAILS_ENV=test
  # bundle exec rake db:migrate RAILS_ENV=production
  [[ -d 'tmp' ]] && touch 'tmp/restart.txt'
fi

if changed 'package.json'; then
  echo "Package.json changed, installing"
  npm install
fi
