#!/bin/bash
# Looks for changes to Gemfile[.lock] or package.json, and automates running bundle and other tasks.
# https://gist.github.com/stefansundin/82051ad2c8565999b914

function changed {
  git diff --name-only HEAD@{2} HEAD | grep "^$1" > /dev/null 2>&1
}

if changed 'Gemfile.*'; then
  echo "Gemfile changed, bundling"
  (bundle check || bundle install) > /dev/null 2>&1 &
  [[ -d 'tmp' ]] && touch 'tmp/restart.txt'
fi

if changed 'bower.json'; then
  echo "bower.json changed, installing"
  bower install > /dev/null 2>&1 &
fi

if changed 'package.json'; then
  echo "Package.json changed, installing"
  npm install > /dev/null 2>&1 &
fi

if changed 'Podfile.*'; then
  echo "Podfile.* changed, installing"
  pod install > /dev/null 2>&1 &
fi
